name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

#    runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: azitmentor
          password: ${{ secrets.dockerpw }}

#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push atishop.product
        uses: docker/build-push-action@v3
        with:
          context: .
#          platforms: linux/amd64,linux/arm64
          push: true
          tags: azitmentor/atitodoapp
      - run: sudo kubectl apply -f deploy/deployment.yml
      - run: sudo kubectl rollout restart deploy/atitodoapp
      # - name: ActionKubeCtl Test
      #   uses: actions-hub/kubectl@master
      #   env:
      #     KUBE_CONFIG: ${{ secrets.KCONFIG }}
      #   with:
      #     args: get pods            
          
      # - name: kubectl test
      #   uses: Consensys/kubernetes-action@master
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KCONFIG }}
      #   with:
      #     args: get pods -A

      # - name: Verify deployment
      #   uses: nickgronow/kubectl@master
      #   with:
      #     config_data: ${{ secrets.KCONFIG }}
      #     args: '"get pods"'

      # - name: Kubernetes deploy
      #   uses: actions-hub/kubectl@master
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KCONFIG }}
      #   with:
      #       args: apply -f deployment.yml

      # - name: Kubernetes rollout restart
      #   uses: actions-hub/kubectl@master
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KCONFIG }}
      #   with:
      #       args: rollout restart deploy/sampleapp
